# Generated by Django 2.1.7 on 2019-03-29 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_auto_20190329_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='statusclass',
            fields=[
                ('statuscode', models.CharField(max_length=1)),
                ('statusmeaning', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_meaning', to='gameplay.statusclass'),
        ),
    ]
