# Generated by Django 2.1.7 on 2019-03-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20190329_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusclass',
            name='statusmeaning',
            field=models.CharField(default='First Player To Move', max_length=300, primary_key=True, serialize=False),
        ),
    ]
