# Generated by Django 2.1.7 on 2019-03-29 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0005_auto_20190329_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_code', to='gameplay.statusclass'),
        ),
    ]
