# Generated by Django 2.1.7 on 2019-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0007_auto_20190329_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(default=True, editable=False),
            preserve_default=False,
        ),
    ]
