# Generated by Django 2.1.7 on 2019-04-02 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0008_move_by_first_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='gameplay.Game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='is_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
